### PR TITLE
Forcing response to array in abstract provider

### PR DESCRIPTION
**Pull request by karllhughes**
As I was building the provider for Careerbuilder, I realized they return only XML objects in their response. This was causing an error in the getJobs method when it tried to pass the $payload into getRawListings as that method expects an array.

I have fixed it by forcing the object to an array and wrote a test for it as well. Please let me know what you think @stevenmaguire

### CODE REVIEW

**Comment by stevenmaguire** [comment]
In the CareerBuilder provider does the `getFormat` method return XML? The response object from Guzzle should convert that already when the format is `xml` instead of the default `json`

**Comment by karllhughes** [comment]
The getFormat method does return XML, but guzzle is returning a SimpleXMLElement Object. I checked it by doing this in the abstract provider:
```
$payload = $response->{$this->getFormat()}();
echo "<pre>"; print_r($payload); exit;
```

**Comment by karllhughes** [comment]
Apparently this is desired behavior from Guzzle: 
http://guzzle3.readthedocs.org/http-client/response.html#json-responses

**Comment by karllhughes** [comment]
I think fixing this is going to require a more comprehensive solution because the whole AbstractProvider expects an array of arrays, not SimpleXML Objects. Closing this for now and going to create a new issue to discuss.

**Pull request closed without merging**
